CREATE TABLE BYTECRUNCHERS.USERS
(ID INTEGER NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(50) NOT NULL UNIQUE,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
PASSWORD CHAR(60) NOT NULL,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL,
IS_ADMIN TINYINT NOT NULL,
PRIMARY KEY (ID))